-------------------------------------------------------
-- 1. LIMPIEZA DE BASE DE DATOS (DROPS SEGUROS)
-------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APPOINTMENT CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTACTO CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECIPE CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VOLUNTARIO_PERFIL CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITAS CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECETAS_MEDICAS CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUSCRIPCION CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PREVISION CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TARIFA_PLAN CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TARIFA_CONSULTA CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPO_CONSULTA CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLAN CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLINICA CASCADE CONSTRAINTS PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOG_ERR_APP'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_ERR_APP CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-----------------------
-- 2. CREACIÓN DE TABLAS
-----------------------

-- LOG DE ERRORES
CREATE SEQUENCE SEQ_LOG_ERR_APP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE LOG_ERR_APP (
    ID_ERROR    NUMBER PRIMARY KEY,
    BLOQUE      VARCHAR2(150),
    MENSAJE     VARCHAR2(4000),
    FECHA_HORA  TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX IX_LOG_ERR_APP_BLOQUE ON LOG_ERR_APP(BLOQUE);

-- CLINICA
CREATE TABLE CLINICA (
  CLINICA_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TIPO_PLAN         VARCHAR2(20),
  NOMBRE_CLINICA    VARCHAR2(100) NOT NULL,
  RUT_CLINICA       VARCHAR2(20)  NOT NULL,
  DIRECCION_CLINICA VARCHAR2(200),
  CIUDAD_CLINICA    VARCHAR2(100),
  REGION_CLINICA    VARCHAR2(100),
  CONSTRAINT uq_clinica_rut UNIQUE (RUT_CLINICA)
  -- Se eliminó el CHECK REGEXP complejo para evitar errores de inserción
);

-- PLAN
CREATE TABLE PLAN (
  PLAN_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODIGO      VARCHAR2(30) NOT NULL,
  TIPO_PLAN   VARCHAR2(20) NOT NULL,
  CONSTRAINT chk_plan_tipo CHECK (TIPO_PLAN IN ('PLAN_FREE','PLAN_PRO')),
  CONSTRAINT uq_plan_codigo UNIQUE (CODIGO)
);

-- PREVISION
CREATE TABLE PREVISION (
  PREVISION_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TIPO_PREVISION VARCHAR2(20) NOT NULL,
  CONSTRAINT chk_prevision_tipo CHECK (TIPO_PREVISION IN ('FONASA','ISAPRE','PARTICULAR')),
  CONSTRAINT uq_prevision_tipo UNIQUE (TIPO_PREVISION)
);

-- TIPO_CONSULTA
CREATE TABLE TIPO_CONSULTA (
  TIPO_CONSULTA_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE_CONSULTA  VARCHAR2(50) NOT NULL,
  CONSTRAINT uq_tipo_consulta_nombre UNIQUE (NOMBRE_CONSULTA)
);

-- PACIENTE
CREATE TABLE PACIENTE (
  PACIENTE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLINICA_ID         NUMBER NOT NULL,
  RUT_PACIENTE       VARCHAR2(20) NOT NULL,
  NOMBRE_PACIENTE    VARCHAR2(100) NOT NULL,
  APELLIDO_PACIENTE  VARCHAR2(100) NOT NULL,
  FECHA_NACIMIENTO   DATE,
  GENERO             VARCHAR2(20),
  TELEFONO           VARCHAR2(20),
  DIRECCION_PACIENTE VARCHAR2(200),
  PREVISION_ID       NUMBER,
  ESTADO             VARCHAR2(20) DEFAULT 'Activo',
  CONSTRAINT uq_paciente_rut UNIQUE (RUT_PACIENTE),
  CONSTRAINT fk_paciente_clinica FOREIGN KEY (CLINICA_ID) REFERENCES CLINICA(CLINICA_ID) ON DELETE CASCADE,
  CONSTRAINT fk_paciente_prevision FOREIGN KEY (PREVISION_ID) REFERENCES PREVISION(PREVISION_ID)
);

-- MEDICO
CREATE TABLE MEDICO (
  MEDICO_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CORREO_MEDICO   VARCHAR2(100) NOT NULL,
  NOMBRE_MEDICO   VARCHAR2(100) NOT NULL,
  APELLIDO_MEDICO VARCHAR2(100) NOT NULL,
  CLINICA_ID      NUMBER NOT NULL,
  ESPECIALIZACION VARCHAR2(100),
  CONSTRAINT fk_medico_clinica FOREIGN KEY (CLINICA_ID) REFERENCES CLINICA(CLINICA_ID) ON DELETE CASCADE,
  CONSTRAINT uq_medico_correo UNIQUE (CORREO_MEDICO)
);

-- CITAS
CREATE TABLE CITAS (
  CITA_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PACIENTE_ID  NUMBER NOT NULL,
  MEDICO_ID    NUMBER NOT NULL,
  FECHA_CITA   DATE NOT NULL,
  HORA_CITA    VARCHAR2(8) NOT NULL,
  MOTIVO       VARCHAR2(255),
  ESTADO       VARCHAR2(50) NOT NULL,
  CONSTRAINT chk_cita_estado CHECK (ESTADO IN ('PENDIENTE','FINALIZADA','CANCELADA','REAGENDADA')),
  CONSTRAINT fk_cita_paciente FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID) ON DELETE CASCADE,
  CONSTRAINT fk_cita_medico FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);

-- RECETAS_MEDICAS
CREATE TABLE RECETAS_MEDICAS (
  RECETA_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PACIENTE_ID     NUMBER NOT NULL,
  MEDICO_ID       NUMBER NOT NULL,
  FECHA_EMISION   DATE DEFAULT SYSDATE NOT NULL,
  MEDICAMENTO     VARCHAR2(100) NOT NULL,
  DOSIS           VARCHAR2(50) NOT NULL,
  INSTRUCCIONES   VARCHAR2(500),
  CONSTRAINT fk_receta_paciente FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID) ON DELETE CASCADE,
  CONSTRAINT fk_receta_medico FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);

-- SUSCRIPCION
CREATE TABLE SUSCRIPCION (
  SUSCRIPCION_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLINICA_ID          NUMBER NOT NULL,
  PLAN_ID             NUMBER NOT NULL,
  FECHA_INICIO        DATE DEFAULT TRUNC(SYSDATE),
  PERIODO_FACTURACION VARCHAR2(10) NOT NULL,
  ESTADO              VARCHAR2(10) NOT NULL,
  CONSTRAINT chk_sus_periodo CHECK (PERIODO_FACTURACION IN ('FREE','MENSUAL','ANUAL')),
  CONSTRAINT chk_sus_estado CHECK (ESTADO IN ('ACTIVA','CANCELADA')),
  CONSTRAINT fk_sus_clinica FOREIGN KEY (CLINICA_ID) REFERENCES CLINICA(CLINICA_ID) ON DELETE CASCADE,
  CONSTRAINT fk_sus_plan FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID)
);

-- TARIFA_PLAN y TARIFA_CONSULTA
CREATE TABLE TARIFA_PLAN (
  TARIFA_PLAN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLAN_ID        NUMBER NOT NULL,
  PRECIO_MENSUAL NUMBER(12,2),
  PRECIO_ANUAL   NUMBER(12,2),
  CONSTRAINT fk_tarifa_plan FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID),
  CONSTRAINT uq_tarifa_plan UNIQUE (PLAN_ID)
);

CREATE TABLE TARIFA_CONSULTA (
  TARIFA_CONSULTA_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TIPO_CONSULTA_ID   NUMBER NOT NULL,
  PREVISION_ID       NUMBER,
  PRECIO             NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_tarifa_prevision FOREIGN KEY (PREVISION_ID) REFERENCES PREVISION(PREVISION_ID),
  CONSTRAINT fk_tarifa_tipocons FOREIGN KEY (TIPO_CONSULTA_ID) REFERENCES TIPO_CONSULTA(TIPO_CONSULTA_ID),
  CONSTRAINT uq_tarifa_consulta UNIQUE (TIPO_CONSULTA_ID, PREVISION_ID)
);

-- DIAGNOSTICO
CREATE TABLE DIAGNOSTICO (
  DIAGNOSTICO_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PACIENTE_ID        NUMBER NOT NULL,
  MEDICO_ID          NUMBER NOT NULL,
  TIPO_CONSULTA_ID   NUMBER NOT NULL,
  NOMBRE_PACIENTE    VARCHAR2(100),
  APELLIDO_PACIENTE  VARCHAR2(100),
  CORREO_PACIENTE    VARCHAR2(100),
  NUM_PACIENTE       VARCHAR2(30),
  NOMBRE_CLINICA     VARCHAR2(150),
  NOMBRE_MEDICO      VARCHAR2(150),
  MENSAJE            VARCHAR2(1000),
  TIPO_PREVISION     VARCHAR2(20),
  RUT_CLINICA        VARCHAR2(20),
  CONSTRAINT fk_diag_paciente  FOREIGN KEY (PACIENTE_ID)      REFERENCES PACIENTE(PACIENTE_ID) ON DELETE CASCADE,
  CONSTRAINT fk_diag_medico    FOREIGN KEY (MEDICO_ID)        REFERENCES MEDICO(MEDICO_ID),
  CONSTRAINT fk_diag_tipocons  FOREIGN KEY (TIPO_CONSULTA_ID) REFERENCES TIPO_CONSULTA(TIPO_CONSULTA_ID)
);

-----------------------
-- 3. INDICES (SIN DUPLICADOS)
-----------------------
-- NOTA: No se crean índices para columnas UNIQUE (RUT_PACIENTE, CORREO_MEDICO, etc.)
-- porque Oracle ya los crea automáticamente.

CREATE INDEX ix_paciente_clinica ON PACIENTE(CLINICA_ID);
CREATE INDEX ix_paciente_prevision ON PACIENTE(PREVISION_ID);

CREATE INDEX ix_medico_clinica ON MEDICO(CLINICA_ID);

CREATE INDEX ix_cita_fecha_estado ON CITAS(FECHA_CITA, ESTADO);
CREATE INDEX ix_cita_medico_fecha ON CITAS(MEDICO_ID, FECHA_CITA);
CREATE INDEX ix_cita_paciente ON CITAS(PACIENTE_ID);

CREATE INDEX ix_receta_paciente ON RECETAS_MEDICAS(PACIENTE_ID);
CREATE INDEX ix_receta_medico ON RECETAS_MEDICAS(MEDICO_ID);
CREATE INDEX ix_receta_fecha ON RECETAS_MEDICAS(FECHA_EMISION);

CREATE INDEX ix_suscripcion_clinica ON SUSCRIPCION(CLINICA_ID);
CREATE INDEX ix_suscripcion_plan ON SUSCRIPCION(PLAN_ID);
CREATE INDEX ix_suscripcion_estado ON SUSCRIPCION(ESTADO);

CREATE INDEX ix_diag_paciente ON DIAGNOSTICO(PACIENTE_ID);
CREATE INDEX ix_diag_medico   ON DIAGNOSTICO(MEDICO_ID);

-------------------------------------------------------
-- 4. POBLADO DE DATOS INICIAL
-------------------------------------------------------

-- 1. Planes
INSERT INTO PLAN (CODIGO, TIPO_PLAN) VALUES ('FREE-001', 'PLAN_FREE');
INSERT INTO PLAN (CODIGO, TIPO_PLAN) VALUES ('PRO-001', 'PLAN_PRO');

-- 2. Clínica (SIN check complex de RUT para asegurar inserción)
INSERT INTO CLINICA (NOMBRE_CLINICA, RUT_CLINICA, TIPO_PLAN, DIRECCION_CLINICA, CIUDAD_CLINICA, REGION_CLINICA) 
VALUES ('Clínica Dr. Fachero Central', '77.123.456-7', 'PLAN_PRO', 'Av. Salud 123', 'Santiago', 'Metropolitana');

-- 3. Previsiones
INSERT INTO PREVISION (TIPO_PREVISION) VALUES ('FONASA');
INSERT INTO PREVISION (TIPO_PREVISION) VALUES ('ISAPRE');
INSERT INTO PREVISION (TIPO_PREVISION) VALUES ('PARTICULAR');

-- 4. Tipos de Consulta
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA) VALUES ('Consulta General');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA) VALUES ('Control Especialista');
INSERT INTO TIPO_CONSULTA (NOMBRE_CONSULTA) VALUES ('Telemedicina');

-- 5. Suscripción
INSERT INTO SUSCRIPCION (CLINICA_ID, PLAN_ID, FECHA_INICIO, PERIODO_FACTURACION, ESTADO)
VALUES (1, 2, SYSDATE, 'MENSUAL', 'ACTIVA');

-- 6. Médico
INSERT INTO MEDICO (CORREO_MEDICO, NOMBRE_MEDICO, APELLIDO_MEDICO, CLINICA_ID, ESPECIALIZACION) 
VALUES ('arturo.cruz@drfachero.cl', 'Arturo', 'Cruz', 1, 'Medicina General');

-- 7. Paciente (Con RUT estándar)
INSERT INTO PACIENTE (CLINICA_ID, RUT_PACIENTE, NOMBRE_PACIENTE, APELLIDO_PACIENTE, FECHA_NACIMIENTO, GENERO, TELEFONO, DIRECCION_PACIENTE, PREVISION_ID, ESTADO) 
VALUES (1, '12.345.678-9', 'Juan', 'Pérez', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Masculino', '987654321', 'Calle Falsa 123', 1, 'Activo');

-- 8. Tarifas
INSERT INTO TARIFA_PLAN (PLAN_ID, PRECIO_MENSUAL, PRECIO_ANUAL) VALUES (2, 45000, 540000);
INSERT INTO TARIFA_CONSULTA (TIPO_CONSULTA_ID, PREVISION_ID, PRECIO) VALUES (1, 1, 5000);

COMMIT;