# =======================================================================
# ORACLE AUTONOMOUS DATABASE - DUCOTIN
# =======================================================================
server.port=8080

# 1. Driver y Dialecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false

# 2. CONNECTION STRING COMPLETO (ducotin_high)
spring.datasource.url=
# 3. CREDENCIALES
spring.datasource.username=ADMIN
spring.datasource.password=

# 4. Configuración SSL - Wallet de Ducotin
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=C:/Users/bmona/api_drfachero/src/main/resources/Wallet_Ducotin
spring.datasource.hikari.data-source-properties.oracle.net.ssl_server_dn_match=false
spring.datasource.hikari.data-source-properties.oracle.net.ssl_version=1.2

# 5. Configuración de HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# 6. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 7. Flyway
spring.flyway.enabled=false

# 8. Logging
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=UnaClaveSecretaLargaYUnicaParaFirmarElJWTDrFachero
jwt.expiration=3600000 
